name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  # Allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        run: |
          git push --force https://dac1992:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/dac1992/watermark-removal-tool main
